name: Origin Repository Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger target repository workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/Tanzeer047/hello-world-repo/dispatches \
            -d '{"event_type":"trigger_workflow","client_payload":{"customField":"customValue"}}'