name: Origin Repository Workflow

on: workflow_dispatch  

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger target repository workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Tanzeer047/hello-world-repo/dispatches \
            -d '{"event_type":"trigger_workflow","client_payload":{"customField":"customValue"}}'
